# Singular Value Decomposition(SVD)
A = U * S * V<sup>T</sup>  
where U and V are unitary matrices  
U = AA<sup>T</sup>  
V = A<sup>T</sup>A  
A<sup>T</sup>A and AA<sup>T</sup> are
1. non-negative positive definite matrix(eigen values >= 0)
2. similar matrices - as their eigen values are same even if their dimension are different (A & B are similar if A = M<sup>-1</sup>*B*M)

In [32]:
import numpy as np
A = np.array([[5,5],[-1,7]])

U = AA<sup>T</sup> = (USV<sup>T</sup>)(USV<sup>T</sup>)<sup>T</sup>  
U = AA<sup>T</sup> = USV<sup>T</sup>VS<sup>T</sup>U<sup>T</sup>         (since V<sup>T</sup>V = I)    
U = AA<sup>T</sup> = USS<sup>T</sup>U<sup>T</sup>    
similarly,  
V = A<sup>T</sup>A = (USV<sup>T</sup>)<sup>T</sup>(USV<sup>T</sup>)  
V = A<sup>T</sup>A = VS<sup>T</sup>U<sup>T</sup>USV<sup>T</sup>         (since U<sup>T</sup>U = I)  
V = A<sup>T</sup>A = VS<sup>T</sup>SV<sup>T</sup>  <br><br>

calculate 
V = eigen vectors of (A<sup>T</sup>A)  and  
S = eigen values of (A<sup>T</sup>A)

In [40]:
S, V = np.linalg.eig(A.T.dot(A))
print(V)
print(S)

[[-0.9486833  -0.31622777]
 [ 0.31622777 -0.9486833 ]]
[20. 80.]


calculate U  
AV = USV<sup>T</sup>V = US

In [42]:
U = A.dot(V)
for i, val in enumerate(np.sqrt(S)):
    U[:,i] = U[:,i]/val
print(U)
S = np.diag(S)

[[-0.70710678 -0.70710678]
 [ 0.70710678 -0.70710678]]


In [46]:
print(U)
print(S)
print(V.T)

[[-0.70710678 -0.70710678]
 [ 0.70710678 -0.70710678]]
[[20.  0.]
 [ 0. 80.]]
[[-0.9486833   0.31622777]
 [-0.31622777 -0.9486833 ]]
